export const HOME = '/';
export const ABOUT  = '/about';
export const PORTFOLIO = '/Portfolio';
export const RESUME = '/resume';
export const TICTAC= '/Portfolio/ticTac';
export const CALCULATOR = '/Portfolio/calculator';
export const SOCIALCARD = '/Portfolio/SocialCard';
export const TEAMPICKER = '/Portfolio/Teampicker';
export const CONTACT = '/Contact';
